environment_root: environments/haas-108
version_root: environments/haas-108/versions

opsman_config_file: environments/haas-108/config/vsphere-opsman.yml
opsman_vars_files: |
  vars/environments/haas-108/opsman.yml
  secrets/product.yml

director_config_file: environments/haas-108/config/director.yml
director_vars_files: |
  vars/environments/haas-108/director.yml
  secrets/product.yml
pks_config_opsfile: |
   config/resource/pivotal-container-service_nsx_security_groups.yml
pas_config_opsfile: |
  config/features/container_networking_interface_plugin-external.yml
  config/resource/diego_brain_nsx_security_groups.yml
  config/resource/router_nsx_security_groups.yml
  config/resource/mysql_proxy_nsx_security_groups.yml
  config/features/haproxy_forward_tls-disable.yml
  config/network/3-az-configuration.yml
pas_vars_files: |
  config/product-default-vars.yml
  config/resource-vars.yml
  config/errand-vars.yml
  vars/environments/haas-108/cf.yml
  secrets/product.yml

healthwatch_config_opsfile: |
  config/features/boshtasks-disable.yml
  config/network/3-az-configuration.yml
healthwatch_vars_files: |
  config/product-default-vars.yml
  config/resource-vars.yml
  config/errand-vars.yml
  vars/environments/haas-108/p-healthwatch.yml

nsxt_vars_files: |
  config/product-default-vars.yml
  vars/environments/haas-108/nsxt.yml
  secrets/product.yml


