---
resource_types:
- name: concourse-pipeline
  type: docker-image
  source:
    repository: concourse/concourse-pipeline-resource
    tag: b792af87749bba0d07b4b894b51b36c679895a28b03b06dcab1847ff5546e4f6
resources:
- name: concourse
  type: concourse-pipeline
  source: ((concourse_source))
- name: pipelines-src
  type: git
  source: ((pipelines_source)) 
jobs:
- name: set-my-pipelines
  plan:
  - get: pipelines-src
    trigger: true
  - put: concourse
    params:
      pipelines_file: pipelines-src/pipelines.yml
