---
resource_types:
- name: concourse-pipeline
  type: docker-image
  source:
    repository: concourse/concourse-pipeline-resource
    tag: 3
resources:
- name: concourse
  type: concourse-pipeline
  source: ((concourse_source))
- name: pipelines-src
  type: git
  source: ((pipelines_source)) 
jobs:
- name: set-my-pipelines
  plan:
  - get: pipelines-src
    trigger: true
  - put: concourse
    params:
      pipelines_file: pipelines-src/pipelines.yml
