concourse_source: 
  target: ((concourse_url))
  insecure: ((concourse_insecure)) # If using vault make sure this is a string type not bool
  teams:
  - name: main
    username: ((concourse_main_username))
    password: ((concourse_main_password))

pipelines_source: 
  uri: ((pipelines_url))

